# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-POST200
version:      0.03
version_from: lib/Apache2/POST200.pm
installdirs:  site
requires:
    Apache::Test:                  
    mod_perl2:                     2.000002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
